#! /bin/bash
make clean
make
ar rcs libcavity.a *.o
make clean 

cp Resonator.h ../MLDOS/
cp Resonator.h ../MLSUM/
cp Resonator.h ../MLDOSSHG/
cp Resonator.h ../MLDOSMaxMinN/
cp Resonator.h ../MLDOSSolar/
cp Resonator.h ../MLDOSEig/

#cp Resonator.h ../MLDOSRHS/
#cp Resonator.h ../MLDOSPOLXY/
#cp Resonator.h ../MLDOSSolar/
#cp Resonator.h ../MLDOSPre/

#cp Resonator.h ../AnalyzeStructure/
#cp Resonator.h ../ComputeQ/
#cp Resonator.h ../FindOpt/