#! /bin/bash

export PETSC_DIR=/home/xdliang/MyLocal/petsc/petsc-3.1-p8
export PETSC_ARCH=arch-debug
export CavityLibPath=$PWD/CodesForLibrary
export NloptLibPath=/usr/local/lib

#/home/xdliang/MyLocal/nlopt_0/.libs
#/home/xdliang/Desktop/Cavity/CleanCodes/nlopt-modify/.libs

cd CodesForLibrary
make clean

cd ../AnalyzeStructure
make clean

cd ../ComputeQ
make clean

cd ../FindOpt
make clean
