#! /bin/bash

export PETSC_DIR=/home/xdliang/MyLocal/petsc
export PETSC_ARCH=arch-opt
export CavityLibPath=$PWD/CodesForLibrary
export NloptLibPath=${HOME}/MyLocal/nlopt/.libs


cd CodesForLibrary
make clean
rm *.a

cd ../MLDOS/
make clean
rm *.h

#cd ../MLDOSRHS/ make clean rm *.h

#cd ../MLDOSPOLXY/ make clean rm *.h

#cd ../MLDOSSolar/ make clean rm *.[oh]

#cd ../MLDOSPre/ make clean rm *.[oh]

