#! /bin/bash

export PETSC_DIR=/home/xdliang/MyLocal/petsc-dev
export PETSC_ARCH=arch-opt
export CavityLibPath=$PWD/CodesForLibrary
#export SLEPC_DIR=/home/xdliang/MyLocal/slepc/slepc-3.1-p6
export NloptLibPath=${HOME}/MyLocal/nlopt_0/.libs


cd CodesForLibrary
bash makelibcavity

cd ../MLDOS
make clean
make

#cd ../MLDOSRHS make clean make

#cd ../MLDOSPOLXY make clean make

#cd ../MLDOSSolar make clean make

#cd ../MLDOSPre make clean make






