#!/bin/bash

# this is a sample to run MLDOSEigCal program;
Nx=168; Ny=168; Nz=1; Mx=136; My=136; Mz=1; Mzslab=0; Npmlx=32; Npmly=32; Npmlz=0;
hx=2.001410953676523e-02;
  
LowerPML=0; BCPeriod=3; Jdirection=3;
bxl=+1; bxu=+1; byl=+1; byu=+1; bzl=+1;bzu=+1;

epsair=1.0; epssub=1.0;
RRT=1e-25; summary="summary.txt";

omega=6.28318530717959e+00;
 
Qabs=1e+25; 
initialdata="TM2DVacR10OptStructure.txt";
filenameComm="ZZZZZ";
filenameSummary="$filenameComm$summary"; 

mpirun -np 2 ~/MyCodes/CavityPETScCodesDev_0/MLDOSEig/MLDOSEigCal -Nx $Nx -Ny $Ny -Nz $Nz -Mx $Mx -My $My -Mz $Mz -Mzslab $Mzslab -Npmlx $Npmlx -Npmly $Npmly -Npmlz $Npmlz -BCPeriod $BCPeriod -bxl $bxl -bxu $bxu  -byl $byl -byu $byu -bzl $bzl -bzu $bzu  -LowerPML $LowerPML -hx $hx -omega $omega -Qabs $Qabs -epsair $epsair -epssub $epssub -RRT $RRT -initialdata $initialdata -filenameComm $filenameComm -mat_ascii_output_large  -eps_monitor -eps_tol 1e-8 -eps_nev 6 -eps_target 0 -eps_target_real  -st_type sinvert -st_ksp_type preonly -st_pc_type lu -st_pc_factor_mat_solver_package mumps| tee $filenameSummary
